name = "Turby"
uuid = "d735d23b-fc84-422d-8d21-ea379f0eb4a3"
version = "0.5.1"
authors = ["Nick Stone <nicholasestone@proton.me>"]

[deps]
BlinkaBoards = "21363b03-61ef-4d89-813f-80ecd0f21085"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
LSM6DS = "79bcc3f4-dd36-4f4f-b281-3a26a374f326"
PCA9685 = "707c5d59-d629-46d8-926b-ce9800519990"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
TSL2591 = "78d368c2-7583-4b1e-891b-543a6de6e000"

[compat]
BlinkaBoards = "0.1.0"
CSVFiles = "1.0.2"
Conda = "1.10.2"
DataFrames = "1.8.0"
Dates = "1.11.0"
FileIO = "1.17.0"
LSM6DS = "0.1.0"
PCA9685 = "0.1.0"
Plots = "1.41.4"
PyCall = "1.96.4"
TSL2591 = "0.1.0"
